backend:
  name: github
  repo: feekar/gardsloten-snickeri
media_folder: src/images
public_folder: images
collections:
  - label: 'Portfolio'
    name: 'portfolio'
    editor:
      preview: false
    folder: src/content/portfolio
    create: true
    fields: 
      - { label: Namn, name: namn, widger: string},
      - { label: Bild, name: image, widget: image },
      - { label: Beskrivning, name: description, widget: string}
      
  - label: 'Startsida'
    name: 'homepage'
    editor:
      preview: false
    files:
      - label: 'Introduktion'
        name: 'introduction'
        file: 'src/content/introduction.md'
        fields:
          - {
              label: introduktion,
              name: introduction,
              widget: object,
              fields:
                [
                  { label: Text, name: text, widget: text },
                  { label: Bild, name: image, widget: image },
                ],
            }
      - label: 'Tjänster'
        name: 'services'
        file: 'src/content/services.md'
        fields:
          - {
              label: Tjänster,
              name: services,
              widget: list,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Bild, name: image, widget: image },
                ]
            }
          # - {label: Titel, name: Titel, widget: markdown}
          # - {label: Text, name: text, widget: text}
          # - {label: Bild, name: image, widget: image}
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "src/testfiles/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}
