backend:
  name: github
  repo: feekar/gardsloten-snickeri
media_folder: static/assets
public_folder: assets
collections:
  - label: "Texter"
    name: "texts"
    files:
      - label: "Startsida"
        name: "homepage"
        file: "src/content/homepageTexts.md"
        fields:
          - {label: Introduktion, name: introductionText, widget: markdown}
          - {label: Möbeltext, name: furnitureText, widget: markdown}
          - {label: Målningstext, name: paintingText, widget: markdown}
   
          
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "src/testfiles/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}